### ISSUE TITLE
Performance, Accessibility, and Browser Testing

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/animal-rescue-website#1]
@charlie-quinn

**Performance Testing**
https://docs.google.com/spreadsheets/d/1w_8S4-4Y8HHuPni6nmJc3hTsfr9t_z97xfD-PDzca4c/edit?usp=sharing

**Accessibility Testing**
https://docs.google.com/spreadsheets/d/1vnxRtvnyfycb6I5pDwf2FKrlIQiL-W1se2gB2HTYpnM/edit?usp=sharing

**Browser Testing**
https://docs.google.com/spreadsheets/d/12-0DzmuLJDotyHIj5kU1kjnJCPvINK4nnGyd9K0S4Ak/edit?usp=sharing

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@juliannastepha ⚠️`Reminder: please close this issue since it has been resolved or expired.`

**Comment by charlie-quinn** [comment]
@juliannastepha ⚠️`Reminder: please close this issue since it has been resolved or expired.`
