### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/animal-rescue-website#2]
@charlie-quinn

There were several issues I faced in this assignment. The most challenging elements were the accessibility elements and the animations. Concerning accessibility, I am still confused whether I applied enough aria-labels, etc. For the animations, it took me a little while to figure out how to animate the buttons on my site when hovered. At first I was overcomplicating the code, but after some trial and error I was able to simplify it. This also improved the overall performance.
I made sure to include something from every unit of this semester, including properly preparing images and SVGs, animations (specifically transitions), accessibility, and performance. All my images and SVGs were properly saved and exported for the web and they were all smushed. All my buttons have animated transitions when hovered. I followed the accessibility checklist while coding my website as well. I also made sure to remove unnecessary code in order to improve the website's performance.
For this assignment, I believe I deserve an A- or A. I've included every possible thing I can think of that we've learned this semester. I'm sure I've forgotten a thing or two, but still I think I was very successful in this assignment.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@juliannastepha ⚠️`Reminder: please close this issue since it has been resolved or expired.`
